using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace OnlineEnrollmentMVC.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "AdminUsers",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FullName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Password = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AdminUsers", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Courses",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Code = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Department = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Schedule = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Units = table.Column<int>(type: "int", nullable: false),
                    Slots = table.Column<int>(type: "int", nullable: false),
                    EnrolledCount = table.Column<int>(type: "int", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Courses", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Students",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FirstName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LastName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Email = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Password = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Phone = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Address = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Program = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    StudentNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BirthDate = table.Column<DateTime>(type: "datetime2", nullable: false),
                    Status = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RegisteredAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Students", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Subjects",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Type = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Units = table.Column<int>(type: "int", nullable: false),
                    YearLevel = table.Column<int>(type: "int", nullable: false),
                    Semester = table.Column<int>(type: "int", nullable: false),
                    CourseId = table.Column<int>(type: "int", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Subjects", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Subjects_Courses_CourseId",
                        column: x => x.CourseId,
                        principalTable: "Courses",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateTable(
                name: "Enrollments",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StudentId = table.Column<int>(type: "int", nullable: false),
                    CourseId = table.Column<int>(type: "int", nullable: false),
                    EnrolledAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Enrollments", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Enrollments_Courses_CourseId",
                        column: x => x.CourseId,
                        principalTable: "Courses",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Enrollments_Students_StudentId",
                        column: x => x.StudentId,
                        principalTable: "Students",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "AdminUsers",
                columns: new[] { "Id", "Email", "FullName", "Password" },
                values: new object[] { 1, "admin@onlineenrollment.com", "Administrator", "admin123" });

            migrationBuilder.InsertData(
                table: "Courses",
                columns: new[] { "Id", "Code", "Department", "EnrolledCount", "IsActive", "Name", "Schedule", "Slots", "Units" },
                values: new object[,]
                {
                    { 1, "BSA", "Business", 0, true, "BS Accountancy", "MWF 7:30-9:00", 40, 24 },
                    { 2, "BSBA", "Business", 0, true, "BS Business Administration", "TTH 7:30-9:00", 40, 24 },
                    { 3, "BSE", "Business", 0, true, "BS Entrepreneurship", "MWF 9:00-10:30", 40, 24 },
                    { 4, "BSME", "Business", 0, true, "BS Management Engineering", "TTH 9:00-10:30", 40, 24 },
                    { 5, "BSCS", "STEM", 0, true, "BS Computer Science", "MWF 7:30-9:00", 40, 24 },
                    { 6, "BSIT", "STEM", 0, true, "BS Information Technology", "TTH 7:30-9:00", 40, 24 },
                    { 7, "BSCE", "STEM", 0, true, "BS Civil Engineering", "MWF 9:00-10:30", 40, 24 },
                    { 8, "BSEE", "STEM", 0, true, "BS Electrical Engineering", "TTH 9:00-10:30", 40, 24 },
                    { 9, "BSBIO", "STEM", 0, true, "BS Biology", "MWF 10:30-12:00", 40, 24 },
                    { 10, "BSN", "STEM", 0, true, "BS Nursing", "TTH 10:30-12:00", 40, 24 },
                    { 11, "BSPSY", "Social Sciences", 0, true, "BS Psychology", "MWF 7:30-9:00", 40, 24 },
                    { 12, "ABCOM", "Social Sciences", 0, true, "AB Communication", "TTH 7:30-9:00", 40, 24 },
                    { 13, "ABPOLSCI", "Social Sciences", 0, true, "AB Political Science", "MWF 9:00-10:30", 40, 24 },
                    { 14, "ABFA", "Social Sciences", 0, true, "AB Fine Arts", "TTH 9:00-10:30", 40, 24 },
                    { 15, "BSED", "Education", 0, true, "BS Secondary Education", "MWF 7:30-9:00", 40, 24 },
                    { 16, "BEED", "Education", 0, true, "BS Elementary Education", "TTH 7:30-9:00", 40, 24 },
                    { 17, "BSARCH", "Education", 0, true, "BS Architecture", "MWF 9:00-10:30", 40, 24 },
                    { 18, "MMA", "Education", 0, true, "Multimedia Arts", "TTH 9:00-10:30", 40, 24 },
                    { 19, "HRM", "General Education", 0, true, "Hotel & Restaurant Management", "MWF 7:30-9:00", 40, 24 },
                    { 20, "BSLM", "General Education", 0, true, "BS Legal Management", "TTH 7:30-9:00", 40, 24 }
                });

            migrationBuilder.InsertData(
                table: "Subjects",
                columns: new[] { "Id", "CourseId", "Name", "Semester", "Type", "Units", "YearLevel" },
                values: new object[,]
                {
                    { 1, null, "English Communication 1", 1, "Minor", 3, 1 },
                    { 2, null, "Mathematics in the Modern World", 1, "Minor", 3, 1 },
                    { 3, null, "Filipino 1", 1, "Minor", 3, 1 },
                    { 4, null, "Life and Works of Rizal", 1, "Minor", 3, 1 },
                    { 5, null, "English Communication 2", 2, "Minor", 3, 1 },
                    { 6, null, "Filipino 2", 2, "Minor", 3, 1 },
                    { 7, null, "Physical Education 1", 2, "Minor", 3, 1 },
                    { 8, null, "National Service Training 1", 2, "Minor", 3, 1 },
                    { 9, null, "Ethics and Moral Philosophy", 1, "Minor", 3, 2 },
                    { 10, null, "Social Science 1", 1, "Minor", 3, 2 },
                    { 11, null, "Physical Education 2", 1, "Minor", 3, 2 },
                    { 12, null, "National Service Training 2", 1, "Minor", 3, 2 },
                    { 13, null, "Philippine History", 2, "Minor", 3, 2 },
                    { 14, null, "Social Science 2", 2, "Minor", 3, 2 },
                    { 15, null, "Physical Education 3", 2, "Minor", 3, 2 },
                    { 16, null, "Art Appreciation", 2, "Minor", 3, 2 },
                    { 17, null, "Environmental Science", 1, "Minor", 3, 3 },
                    { 18, null, "The Contemporary World", 1, "Minor", 3, 3 },
                    { 19, null, "Physical Education 4", 1, "Minor", 3, 3 },
                    { 20, null, "Gender and Society", 1, "Minor", 3, 3 },
                    { 21, null, "Science Technology and Society", 2, "Minor", 3, 3 },
                    { 22, null, "Understanding the Self", 2, "Minor", 3, 3 },
                    { 23, null, "Readings in Philippine History", 2, "Minor", 3, 3 },
                    { 24, null, "Purposive Communication", 2, "Minor", 3, 3 },
                    { 25, null, "The Entrepreneurial Mind", 1, "Minor", 3, 4 },
                    { 26, null, "People and the Earth Ecosystem", 1, "Minor", 3, 4 },
                    { 27, null, "Panitikang Panlipunan", 1, "Minor", 3, 4 },
                    { 28, null, "Kontekstwalisasyon ng Wikang Filipino", 1, "Minor", 3, 4 },
                    { 29, null, "Intro to Research", 2, "Minor", 3, 4 },
                    { 30, null, "Community Engagement", 2, "Minor", 3, 4 },
                    { 31, null, "Internship Seminar", 2, "Minor", 3, 4 },
                    { 32, null, "Values Education", 2, "Minor", 3, 4 },
                    { 33, 1, "Financial Accounting 1", 1, "Major", 3, 1 },
                    { 34, 1, "Management Accounting 1", 1, "Major", 3, 1 },
                    { 35, 1, "Business Law 1", 1, "Major", 3, 1 },
                    { 36, 1, "Economics 1", 1, "Major", 3, 1 },
                    { 37, 1, "Financial Accounting 2", 2, "Major", 3, 1 },
                    { 38, 1, "Management Accounting 2", 2, "Major", 3, 1 },
                    { 39, 1, "Business Law 2", 2, "Major", 3, 1 },
                    { 40, 1, "Economics 2", 2, "Major", 3, 1 },
                    { 41, 1, "Intermediate Accounting 1", 1, "Major", 3, 2 },
                    { 42, 1, "Cost Accounting 1", 1, "Major", 3, 2 },
                    { 43, 1, "Auditing Theory 1", 1, "Major", 3, 2 },
                    { 44, 1, "Taxation 1", 1, "Major", 3, 2 },
                    { 45, 1, "Intermediate Accounting 2", 2, "Major", 3, 2 },
                    { 46, 1, "Cost Accounting 2", 2, "Major", 3, 2 },
                    { 47, 1, "Auditing Theory 2", 2, "Major", 3, 2 },
                    { 48, 1, "Taxation 2", 2, "Major", 3, 2 },
                    { 49, 1, "Advanced Accounting 1", 1, "Major", 3, 3 },
                    { 50, 1, "Auditing Practice 1", 1, "Major", 3, 3 },
                    { 51, 1, "Business Finance 1", 1, "Major", 3, 3 },
                    { 52, 1, "CPA Review 1", 1, "Major", 3, 3 },
                    { 53, 1, "Advanced Accounting 2", 2, "Major", 3, 3 },
                    { 54, 1, "Auditing Practice 2", 2, "Major", 3, 3 },
                    { 55, 1, "Business Finance 2", 2, "Major", 3, 3 },
                    { 56, 1, "CPA Review 2", 2, "Major", 3, 3 },
                    { 57, 1, "Accounting Research 1", 1, "Major", 3, 4 },
                    { 58, 1, "Accounting Systems", 1, "Major", 3, 4 },
                    { 59, 1, "Government Accounting", 1, "Major", 3, 4 },
                    { 60, 1, "Accounting Elective 1", 1, "Major", 3, 4 },
                    { 61, 1, "Accounting Research 2", 2, "Major", 3, 4 },
                    { 62, 1, "Accounting Capstone 1", 2, "Major", 3, 4 },
                    { 63, 1, "Accounting Capstone 2", 2, "Major", 3, 4 },
                    { 64, 1, "Accounting Elective 2", 2, "Major", 3, 4 },
                    { 65, 2, "Principles of Management", 1, "Major", 3, 1 },
                    { 66, 2, "Business Communication 1", 1, "Major", 3, 1 },
                    { 67, 2, "Microeconomics", 1, "Major", 3, 1 },
                    { 68, 2, "Business Math 1", 1, "Major", 3, 1 },
                    { 69, 2, "Business Communication 2", 2, "Major", 3, 1 },
                    { 70, 2, "Organizational Behavior", 2, "Major", 3, 1 },
                    { 71, 2, "Macroeconomics", 2, "Major", 3, 1 },
                    { 72, 2, "Business Math 2", 2, "Major", 3, 1 },
                    { 73, 2, "Human Resource Management", 1, "Major", 3, 2 },
                    { 74, 2, "Marketing Management 1", 1, "Major", 3, 2 },
                    { 75, 2, "Operations Management 1", 1, "Major", 3, 2 },
                    { 76, 2, "Business Finance 1", 1, "Major", 3, 2 },
                    { 77, 2, "Marketing Management 2", 2, "Major", 3, 2 },
                    { 78, 2, "Operations Management 2", 2, "Major", 3, 2 },
                    { 79, 2, "Business Finance 2", 2, "Major", 3, 2 },
                    { 80, 2, "Business Law", 2, "Major", 3, 2 },
                    { 81, 2, "Strategic Management 1", 1, "Major", 3, 3 },
                    { 82, 2, "Entrepreneurship 1", 1, "Major", 3, 3 },
                    { 83, 2, "International Business 1", 1, "Major", 3, 3 },
                    { 84, 2, "Business Research 1", 1, "Major", 3, 3 },
                    { 85, 2, "Strategic Management 2", 2, "Major", 3, 3 },
                    { 86, 2, "Entrepreneurship 2", 2, "Major", 3, 3 },
                    { 87, 2, "International Business 2", 2, "Major", 3, 3 },
                    { 88, 2, "Business Research 2", 2, "Major", 3, 3 },
                    { 89, 2, "Business Ethics", 1, "Major", 3, 4 },
                    { 90, 2, "Supply Chain Management", 1, "Major", 3, 4 },
                    { 91, 2, "Business Policy 1", 1, "Major", 3, 4 },
                    { 92, 2, "BA Elective 1", 1, "Major", 3, 4 },
                    { 93, 2, "Business Capstone 1", 2, "Major", 3, 4 },
                    { 94, 2, "Business Capstone 2", 2, "Major", 3, 4 },
                    { 95, 2, "Business Policy 2", 2, "Major", 3, 4 },
                    { 96, 2, "BA Elective 2", 2, "Major", 3, 4 },
                    { 97, 3, "Intro to Entrepreneurship", 1, "Major", 3, 1 },
                    { 98, 3, "Business Planning 1", 1, "Major", 3, 1 },
                    { 99, 3, "Market Research 1", 1, "Major", 3, 1 },
                    { 100, 3, "Innovation Management 1", 1, "Major", 3, 1 },
                    { 101, 3, "Business Planning 2", 2, "Major", 3, 1 },
                    { 102, 3, "Market Research 2", 2, "Major", 3, 1 },
                    { 103, 3, "Innovation Management 2", 2, "Major", 3, 1 },
                    { 104, 3, "Product Development 1", 2, "Major", 3, 1 },
                    { 105, 3, "Venture Capital 1", 1, "Major", 3, 2 },
                    { 106, 3, "Social Entrepreneurship 1", 1, "Major", 3, 2 },
                    { 107, 3, "Business Model Design 1", 1, "Major", 3, 2 },
                    { 108, 3, "Digital Marketing 1", 1, "Major", 3, 2 },
                    { 109, 3, "Venture Capital 2", 2, "Major", 3, 2 },
                    { 110, 3, "Social Entrepreneurship 2", 2, "Major", 3, 2 },
                    { 111, 3, "Business Model Design 2", 2, "Major", 3, 2 },
                    { 112, 3, "Digital Marketing 2", 2, "Major", 3, 2 },
                    { 113, 3, "Startup Management 1", 1, "Major", 3, 3 },
                    { 114, 3, "Supply Chain Management", 1, "Major", 3, 3 },
                    { 115, 3, "Financial Planning 1", 1, "Major", 3, 3 },
                    { 116, 3, "Entrepreneurship Research 1", 1, "Major", 3, 3 },
                    { 117, 3, "Startup Management 2", 2, "Major", 3, 3 },
                    { 118, 3, "Product Development 2", 2, "Major", 3, 3 },
                    { 119, 3, "Financial Planning 2", 2, "Major", 3, 3 },
                    { 120, 3, "Entrepreneurship Research 2", 2, "Major", 3, 3 },
                    { 121, 3, "Business Scaling 1", 1, "Major", 3, 4 },
                    { 122, 3, "Legal Aspects of Business", 1, "Major", 3, 4 },
                    { 123, 3, "E-Commerce", 1, "Major", 3, 4 },
                    { 124, 3, "Entrepreneurship Elective 1", 1, "Major", 3, 4 },
                    { 125, 3, "Business Scaling 2", 2, "Major", 3, 4 },
                    { 126, 3, "Entrepreneurship Capstone 1", 2, "Major", 3, 4 },
                    { 127, 3, "Entrepreneurship Capstone 2", 2, "Major", 3, 4 },
                    { 128, 3, "Entrepreneurship Elective 2", 2, "Major", 3, 4 },
                    { 129, 4, "Engineering Math 1", 1, "Major", 3, 1 },
                    { 130, 4, "Engineering Drawing 1", 1, "Major", 3, 1 },
                    { 131, 4, "Physics for Engineers 1", 1, "Major", 3, 1 },
                    { 132, 4, "Chemistry for Engineers", 1, "Major", 3, 1 },
                    { 133, 4, "Engineering Math 2", 2, "Major", 3, 1 },
                    { 134, 4, "Engineering Drawing 2", 2, "Major", 3, 1 },
                    { 135, 4, "Physics for Engineers 2", 2, "Major", 3, 1 },
                    { 136, 4, "Statics of Rigid Bodies", 2, "Major", 3, 1 },
                    { 137, 4, "Dynamics", 1, "Major", 3, 2 },
                    { 138, 4, "Thermodynamics 1", 1, "Major", 3, 2 },
                    { 139, 4, "Industrial Engineering 1", 1, "Major", 3, 2 },
                    { 140, 4, "Operations Research 1", 1, "Major", 3, 2 },
                    { 141, 4, "Thermodynamics 2", 2, "Major", 3, 2 },
                    { 142, 4, "Industrial Engineering 2", 2, "Major", 3, 2 },
                    { 143, 4, "Operations Research 2", 2, "Major", 3, 2 },
                    { 144, 4, "Quality Management 1", 2, "Major", 3, 2 },
                    { 145, 4, "Project Management 1", 1, "Major", 3, 3 },
                    { 146, 4, "Systems Engineering 1", 1, "Major", 3, 3 },
                    { 147, 4, "Engineering Economics 1", 1, "Major", 3, 3 },
                    { 148, 4, "ME Research 1", 1, "Major", 3, 3 },
                    { 149, 4, "Project Management 2", 2, "Major", 3, 3 },
                    { 150, 4, "Systems Engineering 2", 2, "Major", 3, 3 },
                    { 151, 4, "Engineering Economics 2", 2, "Major", 3, 3 },
                    { 152, 4, "ME Research 2", 2, "Major", 3, 3 },
                    { 153, 4, "Engineering Management 1", 1, "Major", 3, 4 },
                    { 154, 4, "Safety Engineering", 1, "Major", 3, 4 },
                    { 155, 4, "Production Planning", 1, "Major", 3, 4 },
                    { 156, 4, "ME Elective 1", 1, "Major", 3, 4 },
                    { 157, 4, "Engineering Management 2", 2, "Major", 3, 4 },
                    { 158, 4, "ME Capstone 1", 2, "Major", 3, 4 },
                    { 159, 4, "ME Capstone 2", 2, "Major", 3, 4 },
                    { 160, 4, "ME Elective 2", 2, "Major", 3, 4 },
                    { 161, 5, "Intro to Programming", 1, "Major", 3, 1 },
                    { 162, 5, "Discrete Mathematics 1", 1, "Major", 3, 1 },
                    { 163, 5, "Computer Organization 1", 1, "Major", 3, 1 },
                    { 164, 5, "Data Structures 1", 1, "Major", 3, 1 },
                    { 165, 5, "Object Oriented Programming", 2, "Major", 3, 1 },
                    { 166, 5, "Discrete Mathematics 2", 2, "Major", 3, 1 },
                    { 167, 5, "Computer Organization 2", 2, "Major", 3, 1 },
                    { 168, 5, "Data Structures 2", 2, "Major", 3, 1 },
                    { 169, 5, "Algorithm Design 1", 1, "Major", 3, 2 },
                    { 170, 5, "Operating Systems 1", 1, "Major", 3, 2 },
                    { 171, 5, "Database Systems 1", 1, "Major", 3, 2 },
                    { 172, 5, "Software Engineering 1", 1, "Major", 3, 2 },
                    { 173, 5, "Algorithm Design 2", 2, "Major", 3, 2 },
                    { 174, 5, "Operating Systems 2", 2, "Major", 3, 2 },
                    { 175, 5, "Database Systems 2", 2, "Major", 3, 2 },
                    { 176, 5, "Software Engineering 2", 2, "Major", 3, 2 },
                    { 177, 5, "Computer Networks 1", 1, "Major", 3, 3 },
                    { 178, 5, "Artificial Intelligence 1", 1, "Major", 3, 3 },
                    { 179, 5, "Machine Learning 1", 1, "Major", 3, 3 },
                    { 180, 5, "CS Research 1", 1, "Major", 3, 3 },
                    { 181, 5, "Computer Networks 2", 2, "Major", 3, 3 },
                    { 182, 5, "Artificial Intelligence 2", 2, "Major", 3, 3 },
                    { 183, 5, "Machine Learning 2", 2, "Major", 3, 3 },
                    { 184, 5, "CS Research 2", 2, "Major", 3, 3 },
                    { 185, 5, "Information Security 1", 1, "Major", 3, 4 },
                    { 186, 5, "Distributed Systems", 1, "Major", 3, 4 },
                    { 187, 5, "Compiler Design", 1, "Major", 3, 4 },
                    { 188, 5, "CS Elective 1", 1, "Major", 3, 4 },
                    { 189, 5, "Information Security 2", 2, "Major", 3, 4 },
                    { 190, 5, "CS Capstone 1", 2, "Major", 3, 4 },
                    { 191, 5, "CS Capstone 2", 2, "Major", 3, 4 },
                    { 192, 5, "CS Elective 2", 2, "Major", 3, 4 },
                    { 193, 6, "Intro to IT", 1, "Major", 3, 1 },
                    { 194, 6, "Web Development 1", 1, "Major", 3, 1 },
                    { 195, 6, "Computer Fundamentals", 1, "Major", 3, 1 },
                    { 196, 6, "IT Mathematics 1", 1, "Major", 3, 1 },
                    { 197, 6, "Web Development 2", 2, "Major", 3, 1 },
                    { 198, 6, "IT Mathematics 2", 2, "Major", 3, 1 },
                    { 199, 6, "Database Management 1", 2, "Major", 3, 1 },
                    { 200, 6, "Network Fundamentals 1", 2, "Major", 3, 1 },
                    { 201, 6, "Systems Analysis 1", 1, "Major", 3, 2 },
                    { 202, 6, "Database Management 2", 1, "Major", 3, 2 },
                    { 203, 6, "Network Fundamentals 2", 1, "Major", 3, 2 },
                    { 204, 6, "IT Project Management 1", 1, "Major", 3, 2 },
                    { 205, 6, "Systems Analysis 2", 2, "Major", 3, 2 },
                    { 206, 6, "Mobile Development 1", 2, "Major", 3, 2 },
                    { 207, 6, "IT Project Management 2", 2, "Major", 3, 2 },
                    { 208, 6, "Cloud Computing 1", 2, "Major", 3, 2 },
                    { 209, 6, "Mobile Development 2", 1, "Major", 3, 3 },
                    { 210, 6, "Cloud Computing 2", 1, "Major", 3, 3 },
                    { 211, 6, "Systems Integration 1", 1, "Major", 3, 3 },
                    { 212, 6, "IT Research 1", 1, "Major", 3, 3 },
                    { 213, 6, "Systems Integration 2", 2, "Major", 3, 3 },
                    { 214, 6, "IT Security 1", 2, "Major", 3, 3 },
                    { 215, 6, "IT Research 2", 2, "Major", 3, 3 },
                    { 216, 6, "IT Elective 1", 2, "Major", 3, 3 },
                    { 217, 6, "IT Security 2", 1, "Major", 3, 4 },
                    { 218, 6, "IT Elective 2", 1, "Major", 3, 4 },
                    { 219, 6, "IT Elective 3", 1, "Major", 3, 4 },
                    { 220, 6, "IT Capstone 1", 1, "Major", 3, 4 },
                    { 221, 6, "IT Elective 4", 2, "Major", 3, 4 },
                    { 222, 6, "IT Capstone 2", 2, "Major", 3, 4 },
                    { 223, 6, "IT Capstone 3", 2, "Major", 3, 4 },
                    { 224, 6, "IT Capstone 4", 2, "Major", 3, 4 },
                    { 225, 7, "Engineering Math 1", 1, "Major", 3, 1 },
                    { 226, 7, "Engineering Drawing 1", 1, "Major", 3, 1 },
                    { 227, 7, "Surveying 1", 1, "Major", 3, 1 },
                    { 228, 7, "Statics 1", 1, "Major", 3, 1 },
                    { 229, 7, "Engineering Math 2", 2, "Major", 3, 1 },
                    { 230, 7, "Engineering Drawing 2", 2, "Major", 3, 1 },
                    { 231, 7, "Surveying 2", 2, "Major", 3, 1 },
                    { 232, 7, "Statics 2", 2, "Major", 3, 1 },
                    { 233, 7, "Strength of Materials 1", 1, "Major", 3, 2 },
                    { 234, 7, "Fluid Mechanics 1", 1, "Major", 3, 2 },
                    { 235, 7, "Structural Analysis 1", 1, "Major", 3, 2 },
                    { 236, 7, "Geotechnical Engineering 1", 1, "Major", 3, 2 },
                    { 237, 7, "Strength of Materials 2", 2, "Major", 3, 2 },
                    { 238, 7, "Fluid Mechanics 2", 2, "Major", 3, 2 },
                    { 239, 7, "Structural Analysis 2", 2, "Major", 3, 2 },
                    { 240, 7, "Geotechnical Engineering 2", 2, "Major", 3, 2 },
                    { 241, 7, "Highway Engineering 1", 1, "Major", 3, 3 },
                    { 242, 7, "Construction Management 1", 1, "Major", 3, 3 },
                    { 243, 7, "Structural Design 1", 1, "Major", 3, 3 },
                    { 244, 7, "CE Research 1", 1, "Major", 3, 3 },
                    { 245, 7, "Highway Engineering 2", 2, "Major", 3, 3 },
                    { 246, 7, "Construction Management 2", 2, "Major", 3, 3 },
                    { 247, 7, "Structural Design 2", 2, "Major", 3, 3 },
                    { 248, 7, "CE Research 2", 2, "Major", 3, 3 },
                    { 249, 7, "Environmental Engineering 1", 1, "Major", 3, 4 },
                    { 250, 7, "Water Resources Engineering", 1, "Major", 3, 4 },
                    { 251, 7, "Transportation Engineering", 1, "Major", 3, 4 },
                    { 252, 7, "CE Elective 1", 1, "Major", 3, 4 },
                    { 253, 7, "Environmental Engineering 2", 2, "Major", 3, 4 },
                    { 254, 7, "CE Capstone 1", 2, "Major", 3, 4 },
                    { 255, 7, "CE Capstone 2", 2, "Major", 3, 4 },
                    { 256, 7, "CE Elective 2", 2, "Major", 3, 4 },
                    { 257, 8, "Circuit Theory 1", 1, "Major", 3, 1 },
                    { 258, 8, "Engineering Math 1", 1, "Major", 3, 1 },
                    { 259, 8, "Physics for EE 1", 1, "Major", 3, 1 },
                    { 260, 8, "Engineering Drawing", 1, "Major", 3, 1 },
                    { 261, 8, "Circuit Theory 2", 2, "Major", 3, 1 },
                    { 262, 8, "Engineering Math 2", 2, "Major", 3, 1 },
                    { 263, 8, "Physics for EE 2", 2, "Major", 3, 1 },
                    { 264, 8, "Electronics 1", 2, "Major", 3, 1 },
                    { 265, 8, "Electronics 2", 1, "Major", 3, 2 },
                    { 266, 8, "Electromagnetics 1", 1, "Major", 3, 2 },
                    { 267, 8, "Electrical Machines 1", 1, "Major", 3, 2 },
                    { 268, 8, "Power Systems 1", 1, "Major", 3, 2 },
                    { 269, 8, "Electromagnetics 2", 2, "Major", 3, 2 },
                    { 270, 8, "Electrical Machines 2", 2, "Major", 3, 2 },
                    { 271, 8, "Power Systems 2", 2, "Major", 3, 2 },
                    { 272, 8, "Control Systems 1", 2, "Major", 3, 2 },
                    { 273, 8, "Control Systems 2", 1, "Major", 3, 3 },
                    { 274, 8, "Instrumentation 1", 1, "Major", 3, 3 },
                    { 275, 8, "EE Research 1", 1, "Major", 3, 3 },
                    { 276, 8, "EE Elective 1", 1, "Major", 3, 3 },
                    { 277, 8, "Instrumentation 2", 2, "Major", 3, 3 },
                    { 278, 8, "Power Electronics", 2, "Major", 3, 3 },
                    { 279, 8, "EE Research 2", 2, "Major", 3, 3 },
                    { 280, 8, "EE Elective 2", 2, "Major", 3, 3 },
                    { 281, 8, "High Voltage Engineering", 1, "Major", 3, 4 },
                    { 282, 8, "Renewable Energy Systems", 1, "Major", 3, 4 },
                    { 283, 8, "EE Elective 3", 1, "Major", 3, 4 },
                    { 284, 8, "EE Capstone 1", 1, "Major", 3, 4 },
                    { 285, 8, "EE Elective 4", 2, "Major", 3, 4 },
                    { 286, 8, "EE Capstone 2", 2, "Major", 3, 4 },
                    { 287, 8, "EE Capstone 3", 2, "Major", 3, 4 },
                    { 288, 8, "EE Capstone 4", 2, "Major", 3, 4 },
                    { 289, 9, "General Biology 1", 1, "Major", 3, 1 },
                    { 290, 9, "General Chemistry 1", 1, "Major", 3, 1 },
                    { 291, 9, "Cell Biology 1", 1, "Major", 3, 1 },
                    { 292, 9, "Botany 1", 1, "Major", 3, 1 },
                    { 293, 9, "General Biology 2", 2, "Major", 3, 1 },
                    { 294, 9, "General Chemistry 2", 2, "Major", 3, 1 },
                    { 295, 9, "Cell Biology 2", 2, "Major", 3, 1 },
                    { 296, 9, "Botany 2", 2, "Major", 3, 1 },
                    { 297, 9, "Genetics 1", 1, "Major", 3, 2 },
                    { 298, 9, "Zoology 1", 1, "Major", 3, 2 },
                    { 299, 9, "Ecology 1", 1, "Major", 3, 2 },
                    { 300, 9, "Microbiology 1", 1, "Major", 3, 2 },
                    { 301, 9, "Genetics 2", 2, "Major", 3, 2 },
                    { 302, 9, "Zoology 2", 2, "Major", 3, 2 },
                    { 303, 9, "Ecology 2", 2, "Major", 3, 2 },
                    { 304, 9, "Microbiology 2", 2, "Major", 3, 2 },
                    { 305, 9, "Biochemistry 1", 1, "Major", 3, 3 },
                    { 306, 9, "Evolution 1", 1, "Major", 3, 3 },
                    { 307, 9, "Molecular Biology 1", 1, "Major", 3, 3 },
                    { 308, 9, "Biology Research 1", 1, "Major", 3, 3 },
                    { 309, 9, "Biochemistry 2", 2, "Major", 3, 3 },
                    { 310, 9, "Evolution 2", 2, "Major", 3, 3 },
                    { 311, 9, "Molecular Biology 2", 2, "Major", 3, 3 },
                    { 312, 9, "Biology Research 2", 2, "Major", 3, 3 },
                    { 313, 9, "Biostatistics", 1, "Major", 3, 4 },
                    { 314, 9, "Developmental Biology", 1, "Major", 3, 4 },
                    { 315, 9, "Immunology", 1, "Major", 3, 4 },
                    { 316, 9, "Biology Elective 1", 1, "Major", 3, 4 },
                    { 317, 9, "Bioinformatics", 2, "Major", 3, 4 },
                    { 318, 9, "Biology Capstone 1", 2, "Major", 3, 4 },
                    { 319, 9, "Biology Capstone 2", 2, "Major", 3, 4 },
                    { 320, 9, "Biology Elective 2", 2, "Major", 3, 4 },
                    { 321, 10, "Anatomy and Physiology 1", 1, "Major", 3, 1 },
                    { 322, 10, "Fundamentals of Nursing 1", 1, "Major", 3, 1 },
                    { 323, 10, "Health Assessment 1", 1, "Major", 3, 1 },
                    { 324, 10, "Nutrition 1", 1, "Major", 3, 1 },
                    { 325, 10, "Anatomy and Physiology 2", 2, "Major", 3, 1 },
                    { 326, 10, "Fundamentals of Nursing 2", 2, "Major", 3, 1 },
                    { 327, 10, "Health Assessment 2", 2, "Major", 3, 1 },
                    { 328, 10, "Nutrition 2", 2, "Major", 3, 1 },
                    { 329, 10, "Medical Surgical Nursing 1", 1, "Major", 3, 2 },
                    { 330, 10, "Pharmacology 1", 1, "Major", 3, 2 },
                    { 331, 10, "Microbiology for Nurses", 1, "Major", 3, 2 },
                    { 332, 10, "Maternal Nursing 1", 1, "Major", 3, 2 },
                    { 333, 10, "Medical Surgical Nursing 2", 2, "Major", 3, 2 },
                    { 334, 10, "Pharmacology 2", 2, "Major", 3, 2 },
                    { 335, 10, "Child Nursing", 2, "Major", 3, 2 },
                    { 336, 10, "Maternal Nursing 2", 2, "Major", 3, 2 },
                    { 337, 10, "Psychiatric Nursing 1", 1, "Major", 3, 3 },
                    { 338, 10, "Community Health Nursing 1", 1, "Major", 3, 3 },
                    { 339, 10, "Critical Care Nursing 1", 1, "Major", 3, 3 },
                    { 340, 10, "Nursing Research 1", 1, "Major", 3, 3 },
                    { 341, 10, "Psychiatric Nursing 2", 2, "Major", 3, 3 },
                    { 342, 10, "Community Health Nursing 2", 2, "Major", 3, 3 },
                    { 343, 10, "Critical Care Nursing 2", 2, "Major", 3, 3 },
                    { 344, 10, "Nursing Research 2", 2, "Major", 3, 3 },
                    { 345, 10, "Nursing Leadership 1", 1, "Major", 3, 4 },
                    { 346, 10, "Gerontological Nursing", 1, "Major", 3, 4 },
                    { 347, 10, "Perioperative Nursing", 1, "Major", 3, 4 },
                    { 348, 10, "Nursing Elective 1", 1, "Major", 3, 4 },
                    { 349, 10, "Nursing Leadership 2", 2, "Major", 3, 4 },
                    { 350, 10, "Nursing Review 1", 2, "Major", 3, 4 },
                    { 351, 10, "Nursing Review 2", 2, "Major", 3, 4 },
                    { 352, 10, "Nursing Elective 2", 2, "Major", 3, 4 },
                    { 353, 11, "Intro to Psychology", 1, "Major", 3, 1 },
                    { 354, 11, "Developmental Psychology 1", 1, "Major", 3, 1 },
                    { 355, 11, "Biological Psychology 1", 1, "Major", 3, 1 },
                    { 356, 11, "Research Methods 1", 1, "Major", 3, 1 },
                    { 357, 11, "Developmental Psychology 2", 2, "Major", 3, 1 },
                    { 358, 11, "Biological Psychology 2", 2, "Major", 3, 1 },
                    { 359, 11, "Social Psychology 1", 2, "Major", 3, 1 },
                    { 360, 11, "Research Methods 2", 2, "Major", 3, 1 },
                    { 361, 11, "Social Psychology 2", 1, "Major", 3, 2 },
                    { 362, 11, "Cognitive Psychology 1", 1, "Major", 3, 2 },
                    { 363, 11, "Abnormal Psychology 1", 1, "Major", 3, 2 },
                    { 364, 11, "Psychological Testing 1", 1, "Major", 3, 2 },
                    { 365, 11, "Cognitive Psychology 2", 2, "Major", 3, 2 },
                    { 366, 11, "Abnormal Psychology 2", 2, "Major", 3, 2 },
                    { 367, 11, "Psychological Testing 2", 2, "Major", 3, 2 },
                    { 368, 11, "Counseling Psychology 1", 2, "Major", 3, 2 },
                    { 369, 11, "Counseling Psychology 2", 1, "Major", 3, 3 },
                    { 370, 11, "Industrial Psychology 1", 1, "Major", 3, 3 },
                    { 371, 11, "Health Psychology 1", 1, "Major", 3, 3 },
                    { 372, 11, "Psychology Research 1", 1, "Major", 3, 3 },
                    { 373, 11, "Industrial Psychology 2", 2, "Major", 3, 3 },
                    { 374, 11, "Health Psychology 2", 2, "Major", 3, 3 },
                    { 375, 11, "Neuropsychology 1", 2, "Major", 3, 3 },
                    { 376, 11, "Psychology Research 2", 2, "Major", 3, 3 },
                    { 377, 11, "Neuropsychology 2", 1, "Major", 3, 4 },
                    { 378, 11, "Forensic Psychology", 1, "Major", 3, 4 },
                    { 379, 11, "Psychology Elective 1", 1, "Major", 3, 4 },
                    { 380, 11, "Psychology Capstone 1", 1, "Major", 3, 4 },
                    { 381, 11, "Clinical Psychology", 2, "Major", 3, 4 },
                    { 382, 11, "Psychology Elective 2", 2, "Major", 3, 4 },
                    { 383, 11, "Psychology Capstone 2", 2, "Major", 3, 4 },
                    { 384, 11, "Psychology Capstone 3", 2, "Major", 3, 4 },
                    { 385, 12, "Intro to Communication", 1, "Major", 3, 1 },
                    { 386, 12, "Writing for Media 1", 1, "Major", 3, 1 },
                    { 387, 12, "Speech Communication 1", 1, "Major", 3, 1 },
                    { 388, 12, "Media Studies 1", 1, "Major", 3, 1 },
                    { 389, 12, "Writing for Media 2", 2, "Major", 3, 1 },
                    { 390, 12, "Speech Communication 2", 2, "Major", 3, 1 },
                    { 391, 12, "Media Studies 2", 2, "Major", 3, 1 },
                    { 392, 12, "Broadcast Journalism 1", 2, "Major", 3, 1 },
                    { 393, 12, "Broadcast Journalism 2", 1, "Major", 3, 2 },
                    { 394, 12, "Public Relations 1", 1, "Major", 3, 2 },
                    { 395, 12, "Advertising 1", 1, "Major", 3, 2 },
                    { 396, 12, "Communication Research 1", 1, "Major", 3, 2 },
                    { 397, 12, "Public Relations 2", 2, "Major", 3, 2 },
                    { 398, 12, "Advertising 2", 2, "Major", 3, 2 },
                    { 399, 12, "Communication Research 2", 2, "Major", 3, 2 },
                    { 400, 12, "Digital Media 1", 2, "Major", 3, 2 },
                    { 401, 12, "Digital Media 2", 1, "Major", 3, 3 },
                    { 402, 12, "Film and TV Production 1", 1, "Major", 3, 3 },
                    { 403, 12, "Corporate Communication 1", 1, "Major", 3, 3 },
                    { 404, 12, "Comm Research 3", 1, "Major", 3, 3 },
                    { 405, 12, "Film and TV Production 2", 2, "Major", 3, 3 },
                    { 406, 12, "Corporate Communication 2", 2, "Major", 3, 3 },
                    { 407, 12, "Communication Ethics", 2, "Major", 3, 3 },
                    { 408, 12, "Comm Research 4", 2, "Major", 3, 3 },
                    { 409, 12, "Media Management", 1, "Major", 3, 4 },
                    { 410, 12, "Communication Law", 1, "Major", 3, 4 },
                    { 411, 12, "Communication Elective 1", 1, "Major", 3, 4 },
                    { 412, 12, "Comm Capstone 1", 1, "Major", 3, 4 },
                    { 413, 12, "Communication Elective 2", 2, "Major", 3, 4 },
                    { 414, 12, "Comm Capstone 2", 2, "Major", 3, 4 },
                    { 415, 12, "Comm Capstone 3", 2, "Major", 3, 4 },
                    { 416, 12, "Comm Capstone 4", 2, "Major", 3, 4 },
                    { 417, 13, "Intro to Political Science", 1, "Major", 3, 1 },
                    { 418, 13, "Philippine Government 1", 1, "Major", 3, 1 },
                    { 419, 13, "Political Theory 1", 1, "Major", 3, 1 },
                    { 420, 13, "International Relations 1", 1, "Major", 3, 1 },
                    { 421, 13, "Philippine Government 2", 2, "Major", 3, 1 },
                    { 422, 13, "Political Theory 2", 2, "Major", 3, 1 },
                    { 423, 13, "International Relations 2", 2, "Major", 3, 1 },
                    { 424, 13, "Comparative Politics 1", 2, "Major", 3, 1 },
                    { 425, 13, "Comparative Politics 2", 1, "Major", 3, 2 },
                    { 426, 13, "Public Administration 1", 1, "Major", 3, 2 },
                    { 427, 13, "Political Economy 1", 1, "Major", 3, 2 },
                    { 428, 13, "Public Policy 1", 1, "Major", 3, 2 },
                    { 429, 13, "Public Administration 2", 2, "Major", 3, 2 },
                    { 430, 13, "Political Economy 2", 2, "Major", 3, 2 },
                    { 431, 13, "Public Policy 2", 2, "Major", 3, 2 },
                    { 432, 13, "Constitutional Law 1", 2, "Major", 3, 2 },
                    { 433, 13, "Constitutional Law 2", 1, "Major", 3, 3 },
                    { 434, 13, "Political Research 1", 1, "Major", 3, 3 },
                    { 435, 13, "Local Government", 1, "Major", 3, 3 },
                    { 436, 13, "PolSci Elective 1", 1, "Major", 3, 3 },
                    { 437, 13, "Political Research 2", 2, "Major", 3, 3 },
                    { 438, 13, "International Law", 2, "Major", 3, 3 },
                    { 439, 13, "Electoral Studies", 2, "Major", 3, 3 },
                    { 440, 13, "PolSci Elective 2", 2, "Major", 3, 3 },
                    { 441, 13, "Diplomatic Studies", 1, "Major", 3, 4 },
                    { 442, 13, "Human Rights Law", 1, "Major", 3, 4 },
                    { 443, 13, "PolSci Elective 3", 1, "Major", 3, 4 },
                    { 444, 13, "PolSci Capstone 1", 1, "Major", 3, 4 },
                    { 445, 13, "Peace and Conflict Studies", 2, "Major", 3, 4 },
                    { 446, 13, "PolSci Elective 4", 2, "Major", 3, 4 },
                    { 447, 13, "PolSci Capstone 2", 2, "Major", 3, 4 },
                    { 448, 13, "PolSci Capstone 3", 2, "Major", 3, 4 },
                    { 449, 14, "Drawing 1", 1, "Major", 3, 1 },
                    { 450, 14, "Color Theory 1", 1, "Major", 3, 1 },
                    { 451, 14, "Art History 1", 1, "Major", 3, 1 },
                    { 452, 14, "2D Design 1", 1, "Major", 3, 1 },
                    { 453, 14, "Drawing 2", 2, "Major", 3, 1 },
                    { 454, 14, "Color Theory 2", 2, "Major", 3, 1 },
                    { 455, 14, "Art History 2", 2, "Major", 3, 1 },
                    { 456, 14, "2D Design 2", 2, "Major", 3, 1 },
                    { 457, 14, "Painting 1", 1, "Major", 3, 2 },
                    { 458, 14, "3D Design 1", 1, "Major", 3, 2 },
                    { 459, 14, "Sculpture 1", 1, "Major", 3, 2 },
                    { 460, 14, "Art Criticism 1", 1, "Major", 3, 2 },
                    { 461, 14, "Painting 2", 2, "Major", 3, 2 },
                    { 462, 14, "3D Design 2", 2, "Major", 3, 2 },
                    { 463, 14, "Sculpture 2", 2, "Major", 3, 2 },
                    { 464, 14, "Art Criticism 2", 2, "Major", 3, 2 },
                    { 465, 14, "Digital Art 1", 1, "Major", 3, 3 },
                    { 466, 14, "Printmaking 1", 1, "Major", 3, 3 },
                    { 467, 14, "Photography 1", 1, "Major", 3, 3 },
                    { 468, 14, "Art Research 1", 1, "Major", 3, 3 },
                    { 469, 14, "Digital Art 2", 2, "Major", 3, 3 },
                    { 470, 14, "Printmaking 2", 2, "Major", 3, 3 },
                    { 471, 14, "Photography 2", 2, "Major", 3, 3 },
                    { 472, 14, "Art Research 2", 2, "Major", 3, 3 },
                    { 473, 14, "Portfolio Development 1", 1, "Major", 3, 4 },
                    { 474, 14, "Mixed Media", 1, "Major", 3, 4 },
                    { 475, 14, "Installation Art", 1, "Major", 3, 4 },
                    { 476, 14, "FA Elective 1", 1, "Major", 3, 4 },
                    { 477, 14, "Portfolio Development 2", 2, "Major", 3, 4 },
                    { 478, 14, "FA Capstone 1", 2, "Major", 3, 4 },
                    { 479, 14, "FA Capstone 2", 2, "Major", 3, 4 },
                    { 480, 14, "FA Elective 2", 2, "Major", 3, 4 },
                    { 481, 15, "Intro to Education", 1, "Major", 3, 1 },
                    { 482, 15, "Child Development 1", 1, "Major", 3, 1 },
                    { 483, 15, "The Teaching Profession 1", 1, "Major", 3, 1 },
                    { 484, 15, "Curriculum Dev 1", 1, "Major", 3, 1 },
                    { 485, 15, "Child Development 2", 2, "Major", 3, 1 },
                    { 486, 15, "The Teaching Profession 2", 2, "Major", 3, 1 },
                    { 487, 15, "Curriculum Dev 2", 2, "Major", 3, 1 },
                    { 488, 15, "Assessment 1", 2, "Major", 3, 1 },
                    { 489, 15, "Assessment 2", 1, "Major", 3, 2 },
                    { 490, 15, "Facilitating Learning 1", 1, "Major", 3, 2 },
                    { 491, 15, "Educational Technology 1", 1, "Major", 3, 2 },
                    { 492, 15, "Field Study 1", 1, "Major", 3, 2 },
                    { 493, 15, "Facilitating Learning 2", 2, "Major", 3, 2 },
                    { 494, 15, "Educational Technology 2", 2, "Major", 3, 2 },
                    { 495, 15, "Field Study 2", 2, "Major", 3, 2 },
                    { 496, 15, "Content Area 1", 2, "Major", 3, 2 },
                    { 497, 15, "Content Area 2", 1, "Major", 3, 3 },
                    { 498, 15, "Inclusive Education 1", 1, "Major", 3, 3 },
                    { 499, 15, "Education Research 1", 1, "Major", 3, 3 },
                    { 500, 15, "BSED Elective 1", 1, "Major", 3, 3 },
                    { 501, 15, "Content Area 3", 2, "Major", 3, 3 },
                    { 502, 15, "Inclusive Education 2", 2, "Major", 3, 3 },
                    { 503, 15, "Education Research 2", 2, "Major", 3, 3 },
                    { 504, 15, "BSED Elective 2", 2, "Major", 3, 3 },
                    { 505, 15, "Content Area 4", 1, "Major", 3, 4 },
                    { 506, 15, "Teaching Internship 1", 1, "Major", 3, 4 },
                    { 507, 15, "Classroom Management", 1, "Major", 3, 4 },
                    { 508, 15, "BSED Capstone 1", 1, "Major", 3, 4 },
                    { 509, 15, "Content Area 5", 2, "Major", 3, 4 },
                    { 510, 15, "Teaching Internship 2", 2, "Major", 3, 4 },
                    { 511, 15, "Teaching Internship 3", 2, "Major", 3, 4 },
                    { 512, 15, "BSED Capstone 2", 2, "Major", 3, 4 },
                    { 513, 16, "Foundations of Education", 1, "Major", 3, 1 },
                    { 514, 16, "Child Development 1", 1, "Major", 3, 1 },
                    { 515, 16, "Teaching Reading 1", 1, "Major", 3, 1 },
                    { 516, 16, "Math for Teachers 1", 1, "Major", 3, 1 },
                    { 517, 16, "Child Development 2", 2, "Major", 3, 1 },
                    { 518, 16, "Teaching Reading 2", 2, "Major", 3, 1 },
                    { 519, 16, "Math for Teachers 2", 2, "Major", 3, 1 },
                    { 520, 16, "Science for Teachers 1", 2, "Major", 3, 1 },
                    { 521, 16, "Science for Teachers 2", 1, "Major", 3, 2 },
                    { 522, 16, "Social Studies for Teachers 1", 1, "Major", 3, 2 },
                    { 523, 16, "Assessment in Elementary 1", 1, "Major", 3, 2 },
                    { 524, 16, "Educational Technology 1", 1, "Major", 3, 2 },
                    { 525, 16, "Social Studies for Teachers 2", 2, "Major", 3, 2 },
                    { 526, 16, "Assessment in Elementary 2", 2, "Major", 3, 2 },
                    { 527, 16, "Educational Technology 2", 2, "Major", 3, 2 },
                    { 528, 16, "Special Education 1", 2, "Major", 3, 2 },
                    { 529, 16, "Special Education 2", 1, "Major", 3, 3 },
                    { 530, 16, "Classroom Management 1", 1, "Major", 3, 3 },
                    { 531, 16, "BEED Research 1", 1, "Major", 3, 3 },
                    { 532, 16, "BEED Elective 1", 1, "Major", 3, 3 },
                    { 533, 16, "Classroom Management 2", 2, "Major", 3, 3 },
                    { 534, 16, "Mother Tongue Teaching", 2, "Major", 3, 3 },
                    { 535, 16, "BEED Research 2", 2, "Major", 3, 3 },
                    { 536, 16, "BEED Elective 2", 2, "Major", 3, 3 },
                    { 537, 16, "Values Education Teaching", 1, "Major", 3, 4 },
                    { 538, 16, "Arts and Music Teaching", 1, "Major", 3, 4 },
                    { 539, 16, "Field Study 1", 1, "Major", 3, 4 },
                    { 540, 16, "BEED Capstone 1", 1, "Major", 3, 4 },
                    { 541, 16, "PE and Health Teaching", 2, "Major", 3, 4 },
                    { 542, 16, "Field Study 2", 2, "Major", 3, 4 },
                    { 543, 16, "Teaching Internship", 2, "Major", 3, 4 },
                    { 544, 16, "BEED Capstone 2", 2, "Major", 3, 4 },
                    { 545, 17, "Architectural Design 1", 1, "Major", 3, 1 },
                    { 546, 17, "History of Architecture 1", 1, "Major", 3, 1 },
                    { 547, 17, "Building Technology 1", 1, "Major", 3, 1 },
                    { 548, 17, "Graphics 1", 1, "Major", 3, 1 },
                    { 549, 17, "Architectural Design 2", 2, "Major", 3, 1 },
                    { 550, 17, "History of Architecture 2", 2, "Major", 3, 1 },
                    { 551, 17, "Building Technology 2", 2, "Major", 3, 1 },
                    { 552, 17, "Graphics 2", 2, "Major", 3, 1 },
                    { 553, 17, "Architectural Design 3", 1, "Major", 3, 2 },
                    { 554, 17, "History of Architecture 3", 1, "Major", 3, 2 },
                    { 555, 17, "Building Technology 3", 1, "Major", 3, 2 },
                    { 556, 17, "Structural Systems 1", 1, "Major", 3, 2 },
                    { 557, 17, "Architectural Design 4", 2, "Major", 3, 2 },
                    { 558, 17, "History of Architecture 4", 2, "Major", 3, 2 },
                    { 559, 17, "Building Technology 4", 2, "Major", 3, 2 },
                    { 560, 17, "Structural Systems 2", 2, "Major", 3, 2 },
                    { 561, 17, "Architectural Design 5", 1, "Major", 3, 3 },
                    { 562, 17, "Urban Planning 1", 1, "Major", 3, 3 },
                    { 563, 17, "Environmental Control 1", 1, "Major", 3, 3 },
                    { 564, 17, "Arch Research 1", 1, "Major", 3, 3 },
                    { 565, 17, "Architectural Design 6", 2, "Major", 3, 3 },
                    { 566, 17, "Urban Planning 2", 2, "Major", 3, 3 },
                    { 567, 17, "Environmental Control 2", 2, "Major", 3, 3 },
                    { 568, 17, "Arch Research 2", 2, "Major", 3, 3 },
                    { 569, 17, "Professional Practice 1", 1, "Major", 3, 4 },
                    { 570, 17, "Architectural Utilities 1", 1, "Major", 3, 4 },
                    { 571, 17, "Arch Elective 1", 1, "Major", 3, 4 },
                    { 572, 17, "Arch Thesis 1", 1, "Major", 3, 4 },
                    { 573, 17, "Professional Practice 2", 2, "Major", 3, 4 },
                    { 574, 17, "Architectural Utilities 2", 2, "Major", 3, 4 },
                    { 575, 17, "Arch Elective 2", 2, "Major", 3, 4 },
                    { 576, 17, "Arch Thesis 2", 2, "Major", 3, 4 },
                    { 577, 18, "Intro to Multimedia", 1, "Major", 3, 1 },
                    { 578, 18, "Digital Photography 1", 1, "Major", 3, 1 },
                    { 579, 18, "Graphic Design 1", 1, "Major", 3, 1 },
                    { 580, 18, "Animation Fundamentals 1", 1, "Major", 3, 1 },
                    { 581, 18, "Digital Photography 2", 2, "Major", 3, 1 },
                    { 582, 18, "Graphic Design 2", 2, "Major", 3, 1 },
                    { 583, 18, "Animation Fundamentals 2", 2, "Major", 3, 1 },
                    { 584, 18, "Video Production 1", 2, "Major", 3, 1 },
                    { 585, 18, "Video Production 2", 1, "Major", 3, 2 },
                    { 586, 18, "Web Design 1", 1, "Major", 3, 2 },
                    { 587, 18, "3D Modeling 1", 1, "Major", 3, 2 },
                    { 588, 18, "Motion Graphics 1", 1, "Major", 3, 2 },
                    { 589, 18, "Web Design 2", 2, "Major", 3, 2 },
                    { 590, 18, "3D Modeling 2", 2, "Major", 3, 2 },
                    { 591, 18, "Motion Graphics 2", 2, "Major", 3, 2 },
                    { 592, 18, "Game Design 1", 2, "Major", 3, 2 },
                    { 593, 18, "Game Design 2", 1, "Major", 3, 3 },
                    { 594, 18, "Interactive Media 1", 1, "Major", 3, 3 },
                    { 595, 18, "MMA Research 1", 1, "Major", 3, 3 },
                    { 596, 18, "MMA Elective 1", 1, "Major", 3, 3 },
                    { 597, 18, "Interactive Media 2", 2, "Major", 3, 3 },
                    { 598, 18, "Sound Design", 2, "Major", 3, 3 },
                    { 599, 18, "MMA Research 2", 2, "Major", 3, 3 },
                    { 600, 18, "MMA Elective 2", 2, "Major", 3, 3 },
                    { 601, 18, "Visual Effects 1", 1, "Major", 3, 4 },
                    { 602, 18, "Augmented Reality", 1, "Major", 3, 4 },
                    { 603, 18, "MMA Elective 3", 1, "Major", 3, 4 },
                    { 604, 18, "MMA Capstone 1", 1, "Major", 3, 4 },
                    { 605, 18, "Visual Effects 2", 2, "Major", 3, 4 },
                    { 606, 18, "MMA Elective 4", 2, "Major", 3, 4 },
                    { 607, 18, "MMA Capstone 2", 2, "Major", 3, 4 },
                    { 608, 18, "MMA Capstone 3", 2, "Major", 3, 4 },
                    { 609, 19, "Intro to Hospitality", 1, "Major", 3, 1 },
                    { 610, 19, "Food and Beverage 1", 1, "Major", 3, 1 },
                    { 611, 19, "Front Office Operations 1", 1, "Major", 3, 1 },
                    { 612, 19, "Housekeeping Management 1", 1, "Major", 3, 1 },
                    { 613, 19, "Food and Beverage 2", 2, "Major", 3, 1 },
                    { 614, 19, "Front Office Operations 2", 2, "Major", 3, 1 },
                    { 615, 19, "Housekeeping Management 2", 2, "Major", 3, 1 },
                    { 616, 19, "Culinary Arts 1", 2, "Major", 3, 1 },
                    { 617, 19, "Culinary Arts 2", 1, "Major", 3, 2 },
                    { 618, 19, "Hotel Operations 1", 1, "Major", 3, 2 },
                    { 619, 19, "Tourism Management 1", 1, "Major", 3, 2 },
                    { 620, 19, "Event Management 1", 1, "Major", 3, 2 },
                    { 621, 19, "Hotel Operations 2", 2, "Major", 3, 2 },
                    { 622, 19, "Tourism Management 2", 2, "Major", 3, 2 },
                    { 623, 19, "Event Management 2", 2, "Major", 3, 2 },
                    { 624, 19, "Resort Management 1", 2, "Major", 3, 2 },
                    { 625, 19, "Resort Management 2", 1, "Major", 3, 3 },
                    { 626, 19, "Food Safety 1", 1, "Major", 3, 3 },
                    { 627, 19, "HRM Research 1", 1, "Major", 3, 3 },
                    { 628, 19, "HRM Elective 1", 1, "Major", 3, 3 },
                    { 629, 19, "Food Safety 2", 2, "Major", 3, 3 },
                    { 630, 19, "Hospitality Marketing", 2, "Major", 3, 3 },
                    { 631, 19, "HRM Research 2", 2, "Major", 3, 3 },
                    { 632, 19, "HRM Elective 2", 2, "Major", 3, 3 },
                    { 633, 19, "Revenue Management", 1, "Major", 3, 4 },
                    { 634, 19, "Convention Management", 1, "Major", 3, 4 },
                    { 635, 19, "HRM Elective 3", 1, "Major", 3, 4 },
                    { 636, 19, "HRM Capstone 1", 1, "Major", 3, 4 },
                    { 637, 19, "Sustainable Tourism", 2, "Major", 3, 4 },
                    { 638, 19, "HRM Elective 4", 2, "Major", 3, 4 },
                    { 639, 19, "HRM Capstone 2", 2, "Major", 3, 4 },
                    { 640, 19, "HRM Capstone 3", 2, "Major", 3, 4 },
                    { 641, 20, "Intro to Law", 1, "Major", 3, 1 },
                    { 642, 20, "Obligations and Contracts 1", 1, "Major", 3, 1 },
                    { 643, 20, "Legal Research 1", 1, "Major", 3, 1 },
                    { 644, 20, "Political Law 1", 1, "Major", 3, 1 },
                    { 645, 20, "Obligations and Contracts 2", 2, "Major", 3, 1 },
                    { 646, 20, "Legal Research 2", 2, "Major", 3, 1 },
                    { 647, 20, "Political Law 2", 2, "Major", 3, 1 },
                    { 648, 20, "Criminal Law 1", 2, "Major", 3, 1 },
                    { 649, 20, "Criminal Law 2", 1, "Major", 3, 2 },
                    { 650, 20, "Civil Law 1", 1, "Major", 3, 2 },
                    { 651, 20, "Corporation Law 1", 1, "Major", 3, 2 },
                    { 652, 20, "Labor Law 1", 1, "Major", 3, 2 },
                    { 653, 20, "Civil Law 2", 2, "Major", 3, 2 },
                    { 654, 20, "Corporation Law 2", 2, "Major", 3, 2 },
                    { 655, 20, "Labor Law 2", 2, "Major", 3, 2 },
                    { 656, 20, "Taxation Law 1", 2, "Major", 3, 2 },
                    { 657, 20, "Taxation Law 2", 1, "Major", 3, 3 },
                    { 658, 20, "Evidence 1", 1, "Major", 3, 3 },
                    { 659, 20, "Legal Writing 1", 1, "Major", 3, 3 },
                    { 660, 20, "LM Elective 1", 1, "Major", 3, 3 },
                    { 661, 20, "Evidence 2", 2, "Major", 3, 3 },
                    { 662, 20, "International Law 1", 2, "Major", 3, 3 },
                    { 663, 20, "Legal Writing 2", 2, "Major", 3, 3 },
                    { 664, 20, "LM Elective 2", 2, "Major", 3, 3 },
                    { 665, 20, "International Law 2", 1, "Major", 3, 4 },
                    { 666, 20, "Legal Management Elective 1", 1, "Major", 3, 4 },
                    { 667, 20, "LM Elective 3", 1, "Major", 3, 4 },
                    { 668, 20, "LM Capstone 1", 1, "Major", 3, 4 },
                    { 669, 20, "ADR and Arbitration", 2, "Major", 3, 4 },
                    { 670, 20, "Legal Management Elective 2", 2, "Major", 3, 4 },
                    { 671, 20, "LM Capstone 2", 2, "Major", 3, 4 },
                    { 672, 20, "LM Capstone 3", 2, "Major", 3, 4 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Enrollments_CourseId",
                table: "Enrollments",
                column: "CourseId");

            migrationBuilder.CreateIndex(
                name: "IX_Enrollments_StudentId",
                table: "Enrollments",
                column: "StudentId");

            migrationBuilder.CreateIndex(
                name: "IX_Subjects_CourseId",
                table: "Subjects",
                column: "CourseId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AdminUsers");

            migrationBuilder.DropTable(
                name: "Enrollments");

            migrationBuilder.DropTable(
                name: "Subjects");

            migrationBuilder.DropTable(
                name: "Students");

            migrationBuilder.DropTable(
                name: "Courses");
        }
    }
}
